require('dotenv').config();

let {
	REACT_APP_BUTTON_COLOR,
	REACT_APP_LINEAR_COLOR,
	REACT_APP_TIFFANY_BLUE_COLOR,
	REACT_APP_PRIMARY_COLOR,
	REACT_APP_LIGHT_GREEN_COLOR,
	REACT_APP_SECONDARY_COLOR,
	REACT_APP_BACKGROUND_COLOR,
	REACT_APP_WHITE_COLOR,
	REACT_APP_TITLE_FONT_FAMILY,
	REACT_APP_TITLE_FONT_SIZE,
	REACT_APP_SUBTITLE_FONT_FAMILY,
	REACT_APP_SUBTITLE_FONT_SIZE,
	REACT_APP_TEXT_FONT_FAMILY,
	REACT_APP_TEXT_FONT_SIZE,
	REACT_APP_LOGO_NAME,
	REACT_APP_BRAND_XS_LOGO_NAME,
	REACT_APP_BG_IMG_NAME,
	REACT_APP_LABEL_COLOR,
	REACT_APP_SUCCESS_COLOR,
	REACT_APP_DANGER_COLOR
} = process.env;

const colors = {
	button: REACT_APP_BUTTON_COLOR || '#0dbab1',
	linearGreen: REACT_APP_LINEAR_COLOR || '#78e289',
	tiffanyBlue: REACT_APP_TIFFANY_BLUE_COLOR || '#21D4FD',
	lightGreen: REACT_APP_LIGHT_GREEN_COLOR || '#09daea',
	primary: REACT_APP_PRIMARY_COLOR || '#23a883',
	secondary: REACT_APP_SECONDARY_COLOR || '#49b395',
	lightBg: REACT_APP_SECONDARY_COLOR || '#144654',
	background: REACT_APP_BACKGROUND_COLOR || '#0D282F',
	darkBg: REACT_APP_BACKGROUND_COLOR || '#021921',
	white: REACT_APP_WHITE_COLOR || '#fff',
	label: REACT_APP_LABEL_COLOR || '#b8b9ba',
	success: REACT_APP_SUCCESS_COLOR || '#33D68A',
	danger: REACT_APP_DANGER_COLOR || '#fc6058'
};

const logo = REACT_APP_LOGO_NAME || 'brandIcon.webp';
const brandXsLogo = REACT_APP_BRAND_XS_LOGO_NAME || 'brand-xs-icon.webp';
const backgroundImg = REACT_APP_BG_IMG_NAME || 'blockchain-bg.gif';

const fonts = {
	titleFontFamily: REACT_APP_TITLE_FONT_FAMILY || 'Khula',
	titleFontSize: REACT_APP_TITLE_FONT_SIZE || 24,
	subtitleFontFamily: REACT_APP_SUBTITLE_FONT_FAMILY || 'Khula',
	subtitleFontSize: REACT_APP_SUBTITLE_FONT_SIZE || 16,
	textFontFamily: REACT_APP_TEXT_FONT_FAMILY || 'Khula',
	textFontSize: REACT_APP_TEXT_FONT_SIZE || 14
};

export { colors, fonts, logo, brandXsLogo, backgroundImg };
